<?php

namespace ShortUrlBundle\Repository;

/**
 * ShortUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortUrlRepository extends \Doctrine\ORM\EntityRepository
{
}
